#!/bin/bash

# 无人机UDP通信测试系统 - 使用示例

echo "=========================================="
echo "    无人机UDP通信测试系统 - 使用示例"
echo "=========================================="
echo ""

echo "1. 基本测试（不含GPS和Nexfi记录）"
echo "----------------------------------------"
echo "# 无人机A (发送端)"
echo "./start_test.sh sender"
echo ""
echo "# 无人机B (接收端)"
echo "./start_test.sh receiver"
echo ""

echo "2. 含GPS记录的测试"
echo "----------------------------------------"
echo "# 无人机A (发送端)"
echo "./start_test.sh sender --enable-gps --drone-id=drone0"
echo ""
echo "# 无人机B (接收端)"
echo "./start_test.sh receiver --enable-gps --drone-id=drone1"
echo ""

echo "3. 含Nexfi通信状态记录的测试"
echo "----------------------------------------"
echo "# 无人机A (发送端)"
echo "./start_test.sh sender --enable-nexfi --nexfi-ip=192.168.104.1"
echo ""
echo "# 无人机B (接收端)"
echo "./start_test.sh receiver --enable-nexfi --nexfi-ip=192.168.104.1"
echo ""

echo "4. 全功能测试（GPS + Nexfi + UDP）"
echo "----------------------------------------"
echo "# 无人机A (发送端)"
echo "./start_test.sh sender --enable-gps --drone-id=drone0 --enable-nexfi --time=300"
echo ""
echo "# 无人机B (接收端)"
echo "./start_test.sh receiver --enable-gps --drone-id=drone1 --enable-nexfi --time=300"
echo ""

echo "5. 自定义参数测试"
echo "----------------------------------------"
echo "# 高频发送测试 (50Hz)"
echo "./start_test.sh sender --frequency=50 --packet-size=500 --time=120"
echo ""
echo "# 长时间测试 (1小时)"
echo "./start_test.sh receiver --time=3600"
echo ""

echo "6. 独立运行各组件"
echo "----------------------------------------"
echo "# 单独运行GPS记录器"
echo "python3 gps.py --drone-id=drone0 --interval=0.5 --time=300"
echo ""
echo "# 单独运行Nexfi状态记录器"
echo "python3 nexfi_client.py --nexfi-ip=192.168.104.1 --interval=1.0 --time=300"
echo ""
echo "# Nexfi监控模式"
echo "python3 nexfi_client.py --nexfi-ip=192.168.104.1 --monitor=5"
echo ""

echo "7. 数据分析示例"
echo "----------------------------------------"
echo "# 查看最新的日志文件"
echo "ls -lt logs/ | head -10"
echo ""
echo "# 实时查看UDP接收日志"
echo "tail -f logs/udp_receiver_*.csv"
echo ""
echo "# 查看系统监控状态"
echo "tail -f logs/system_monitor.jsonl | jq ."
echo ""

echo "8. 故障排查"
echo "----------------------------------------"
echo "# 测试网络连接"
echo "ping 192.168.104.20"
echo ""
echo "# 测试Nexfi设备连接"
echo "curl http://192.168.104.1"
echo ""
echo "# 检查时间同步状态"
echo "chronyc sources -v"
echo ""
echo "# 检查ROS2环境（GPS需要）"
echo "ros2 topic list"
echo ""

echo "=========================================="
echo "更多信息请查看: README_NTP_INTEGRATION.md"
echo "==========================================" 