#!/bin/bash

# 无人机UDP通信测试系统 - 使用示例脚本
# 本脚本展示了不同场景下的使用方法

# 颜色定义
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}=========================================="
echo "无人机UDP通信测试系统 - 使用示例"
echo -e "==========================================${NC}"
echo ""

echo -e "${YELLOW}⚠️  重要提醒：所有测试前请先激活虚拟环境${NC}"
echo "source venv/bin/activate"
echo ""

echo -e "${GREEN}1. 基本测试（不含GPS记录）${NC}"
echo "适用于：基础通信测试，不需要位置信息"
echo ""
echo "无人机A (发送端):"
echo "source venv/bin/activate"
echo "./start_test.sh sender --local-ip=192.168.104.10 --peer-ip=192.168.104.20"
echo ""
echo "无人机B (接收端):"
echo "source venv/bin/activate"
echo "./start_test.sh receiver --local-ip=192.168.104.20 --peer-ip=192.168.104.10"
echo ""
echo "----------------------------------------"
echo ""

echo -e "${GREEN}2. 完整测试（含GPS记录）${NC}"
echo "适用于：需要记录飞行轨迹的测试"
echo ""
echo "无人机A (发送端):"
echo "source venv/bin/activate"
echo "./start_test.sh sender --local-ip=192.168.104.10 --peer-ip=192.168.104.20 --enable-gps --drone-id=drone0"
echo ""
echo "无人机B (接收端):"
echo "source venv/bin/activate"
echo "./start_test.sh receiver --local-ip=192.168.104.20 --peer-ip=192.168.104.10 --enable-gps --drone-id=drone1"
echo ""
echo "----------------------------------------"
echo ""

echo -e "${GREEN}3. 高频测试（20Hz发送，0.5秒GPS记录）${NC}"
echo "适用于：高精度通信测试"
echo ""
echo "无人机A (发送端):"
echo "source venv/bin/activate"
echo "./start_test.sh sender --frequency=20 --enable-gps --gps-interval=0.5 --time=300"
echo ""
echo "无人机B (接收端):"
echo "source venv/bin/activate"
echo "./start_test.sh receiver --enable-gps --gps-interval=0.5 --time=300"
echo ""
echo "----------------------------------------"
echo ""

echo -e "${GREEN}4. 长时间测试（10分钟）${NC}"
echo "适用于：稳定性测试"
echo ""
echo "无人机A (发送端):"
echo "source venv/bin/activate"
echo "./start_test.sh sender --time=600 --enable-gps"
echo ""
echo "无人机B (接收端):"
echo "source venv/bin/activate"
echo "./start_test.sh receiver --time=600 --enable-gps"
echo ""
echo "----------------------------------------"
echo ""

echo -e "${GREEN}5. 仿真环境测试${NC}"
echo "适用于：Gazebo仿真环境"
echo ""
echo "无人机A (发送端):"
echo "source venv/bin/activate"
echo "./start_test.sh sender --enable-gps --use-sim-time --drone-id=drone0"
echo ""
echo "无人机B (接收端):"
echo "source venv/bin/activate"
echo "./start_test.sh receiver --enable-gps --use-sim-time --drone-id=drone1"
echo ""
echo "----------------------------------------"
echo ""

echo -e "${GREEN}6. 自定义网络配置${NC}"
echo "适用于：非标准IP地址"
echo ""
echo "无人机A (192.168.1.100):"
echo "source venv/bin/activate"
echo "./start_test.sh sender --local-ip=192.168.1.100 --peer-ip=192.168.1.101 --enable-gps --drone-id=uav_alpha"
echo ""
echo "无人机B (192.168.1.101):"
echo "source venv/bin/activate"
echo "./start_test.sh receiver --local-ip=192.168.1.101 --peer-ip=192.168.1.100 --enable-gps --drone-id=uav_beta"
echo ""
echo "----------------------------------------"
echo ""

echo -e "${GREEN}7. 独立GPS记录${NC}"
echo "适用于：只记录GPS数据，不进行通信测试"
echo ""
echo "基本GPS记录 (1秒间隔，5分钟):"
echo "source venv/bin/activate"
echo "python3 gps.py --drone-id=drone0 --interval=1.0 --time=300"
echo ""
echo "高频GPS记录 (0.1秒间隔，10分钟):"
echo "source venv/bin/activate"
echo "python3 gps.py --drone-id=drone0 --interval=0.1 --time=600"
echo ""
echo "仿真环境GPS记录:"
echo "source venv/bin/activate"
echo "python3 gps.py --drone-id=drone0 --sim-time --log-path=./sim_logs"
echo ""
echo "----------------------------------------"
echo ""

echo -e "${YELLOW}使用提示：${NC}"
echo "1. 运行 ./setup.sh 完成环境部署"
echo "2. 每次使用前激活虚拟环境: source venv/bin/activate"
echo "3. 确保两台无人机在同一网段"
echo "4. 启用GPS记录需要ROS2环境"
echo "5. 建议先运行接收端，再运行发送端"
echo "6. 测试期间保持网络连接稳定"
echo "7. 查看日志文件了解详细结果"
echo ""

echo -e "${YELLOW}常用检查命令：${NC}"
echo "检查环境部署: ./check_environment.sh"
echo "检查网络连接: ping 192.168.104.20"
echo "检查ROS2环境: echo \$ROS_DISTRO"
echo "检查GPS话题: ros2 topic list | grep gps"
echo "查看实时日志: tail -f ./logs/system_monitor.jsonl"
echo ""

echo -e "${BLUE}更多详细信息请查看 README_NTP_INTEGRATION.md${NC}" 